version: '3'

services:
  reverse-proxy:
    image: reverse-proxy
    build:
      context: .
    container_name: reverse-proxy
    depends_on:
      - hello-world-service
      - goodbye-world-service
    ports:
      - 8080:80
    restart: on-failure

  hello-world-service:
    image: hello-world-service
    container_name: hello-world-service
    build:
      context: ./hello-world-service
    ports:
      - 8081:8080
    restart: on-failure

  goodbye-world-service:
    image: goodbye-world-service
    container_name: goodbye-world-service
    build:
      context: ./goodbye-world-service
    ports:
      - 8082:8080
    restart: on-failure
